# Generated by Django 5.1.4 on 2025-04-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Small (under 20 lbs)'), ('medium', 'Medium (20-50 lbs)'), ('large', 'Large (50-90 lbs)')], max_length=10),
        ),
    ]
