# Generated by Django 5.1.4 on 2025-04-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dog_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(blank=True, choices=[('beagle', 'Beagle'), ('bhote', 'Bhote Kukur'), ('boxer', 'Boxer'), ('bulldog', 'Bulldog'), ('chihuahua', 'Chihuahua'), ('cocker', 'Cocker Spaniel'), ('dalmatian', 'Dalmatian'), ('damchi', 'Damchi'), ('german', 'German Shepherd'), ('golden', 'Golden Retriever'), ('husky', 'Siberian Husky'), ('japanese', 'Japanese Spitz'), ('lab', 'Labrador Retriever'), ('lhasa', 'Lhasa Apso'), ('maltese', 'Maltese'), ('pomeranian', 'Pomeranian'), ('poodle', 'Poodle'), ('pug', 'Pug'), ('rottweiler', 'Rottweiler'), ('shih', 'Shih Tzu'), ('spaniel', 'English Springer Spaniel'), ('tibetan', 'Tibetan Mastiff'), ('yorkie', 'Yorkshire Terrier')], max_length=100),
        ),
    ]
